// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// corr_qr_fit
SEXP corr_qr_fit(SEXP par_, SEXP x_, SEXP y_, SEXP hyper, SEXP dim_, SEXP gridpars, SEXP tauG, SEXP muV_, SEXP SV_, SEXP blocks_, SEXP blockSizes_, SEXP dmcmcpar, SEXP imcmcpar);
RcppExport SEXP corrQR_corr_qr_fit(SEXP par_SEXP, SEXP x_SEXP, SEXP y_SEXP, SEXP hyperSEXP, SEXP dim_SEXP, SEXP gridparsSEXP, SEXP tauGSEXP, SEXP muV_SEXP, SEXP SV_SEXP, SEXP blocks_SEXP, SEXP blockSizes_SEXP, SEXP dmcmcparSEXP, SEXP imcmcparSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type par_(par_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type x_(x_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type hyper(hyperSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dim_(dim_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type gridpars(gridparsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauG(tauGSEXP);
    Rcpp::traits::input_parameter< SEXP >::type muV_(muV_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type SV_(SV_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type blocks_(blocks_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type blockSizes_(blockSizes_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type dmcmcpar(dmcmcparSEXP);
    Rcpp::traits::input_parameter< SEXP >::type imcmcpar(imcmcparSEXP);
    __result = Rcpp::wrap(corr_qr_fit(par_, x_, y_, hyper, dim_, gridpars, tauG, muV_, SV_, blocks_, blockSizes_, dmcmcpar, imcmcpar));
    return __result;
END_RCPP
}
