// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// corr_qr_fit
SEXP corr_qr_fit(SEXP par_, SEXP x_, SEXP y_, SEXP hyper_, SEXP dim_, SEXP A_, SEXP R_, SEXP LOGDET_, SEXP LPGRID_, SEXP tauG_, SEXP muV_, SEXP SV_, SEXP blocks_, SEXP blockSizes_, SEXP dmcmcpar_, SEXP imcmcpar_);
RcppExport SEXP corrQR_corr_qr_fit(SEXP par_SEXP, SEXP x_SEXP, SEXP y_SEXP, SEXP hyper_SEXP, SEXP dim_SEXP, SEXP A_SEXP, SEXP R_SEXP, SEXP LOGDET_SEXP, SEXP LPGRID_SEXP, SEXP tauG_SEXP, SEXP muV_SEXP, SEXP SV_SEXP, SEXP blocks_SEXP, SEXP blockSizes_SEXP, SEXP dmcmcpar_SEXP, SEXP imcmcpar_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type par_(par_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type x_(x_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type hyper_(hyper_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type dim_(dim_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_(R_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type LOGDET_(LOGDET_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type LPGRID_(LPGRID_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauG_(tauG_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type muV_(muV_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type SV_(SV_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type blocks_(blocks_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type blockSizes_(blockSizes_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type dmcmcpar_(dmcmcpar_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type imcmcpar_(imcmcpar_SEXP);
    rcpp_result_gen = Rcpp::wrap(corr_qr_fit(par_, x_, y_, hyper_, dim_, A_, R_, LOGDET_, LPGRID_, tauG_, muV_, SV_, blocks_, blockSizes_, dmcmcpar_, imcmcpar_));
    return rcpp_result_gen;
END_RCPP
}
// devianceCalc
SEXP devianceCalc(SEXP pars_, SEXP x_, SEXP y_, SEXP hyper_, SEXP dim_, SEXP A_, SEXP R_, SEXP LOGDET_, SEXP LPGRID_, SEXP tauG_);
RcppExport SEXP corrQR_devianceCalc(SEXP pars_SEXP, SEXP x_SEXP, SEXP y_SEXP, SEXP hyper_SEXP, SEXP dim_SEXP, SEXP A_SEXP, SEXP R_SEXP, SEXP LOGDET_SEXP, SEXP LPGRID_SEXP, SEXP tauG_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type pars_(pars_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type x_(x_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type y_(y_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type hyper_(hyper_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type dim_(dim_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_(R_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type LOGDET_(LOGDET_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type LPGRID_(LPGRID_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauG_(tauG_SEXP);
    rcpp_result_gen = Rcpp::wrap(devianceCalc(pars_, x_, y_, hyper_, dim_, A_, R_, LOGDET_, LPGRID_, tauG_));
    return rcpp_result_gen;
END_RCPP
}
// bivarDensity
SEXP bivarDensity(SEXP newX_, SEXP selectY_, SEXP neval_, SEXP ngrid_, SEXP Yeval_, SEXP Yres_, SEXP pSamples_, SEXP hyper_, SEXP dim_, SEXP A_, SEXP R_, SEXP LOGDET_, SEXP LPGRID_, SEXP tauG_, SEXP summaryType_);
RcppExport SEXP corrQR_bivarDensity(SEXP newX_SEXP, SEXP selectY_SEXP, SEXP neval_SEXP, SEXP ngrid_SEXP, SEXP Yeval_SEXP, SEXP Yres_SEXP, SEXP pSamples_SEXP, SEXP hyper_SEXP, SEXP dim_SEXP, SEXP A_SEXP, SEXP R_SEXP, SEXP LOGDET_SEXP, SEXP LPGRID_SEXP, SEXP tauG_SEXP, SEXP summaryType_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type newX_(newX_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type selectY_(selectY_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type neval_(neval_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type ngrid_(ngrid_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Yeval_(Yeval_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type Yres_(Yres_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type pSamples_(pSamples_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type hyper_(hyper_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type dim_(dim_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type A_(A_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_(R_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type LOGDET_(LOGDET_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type LPGRID_(LPGRID_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauG_(tauG_SEXP);
    Rcpp::traits::input_parameter< SEXP >::type summaryType_(summaryType_SEXP);
    rcpp_result_gen = Rcpp::wrap(bivarDensity(newX_, selectY_, neval_, ngrid_, Yeval_, Yres_, pSamples_, hyper_, dim_, A_, R_, LOGDET_, LPGRID_, tauG_, summaryType_));
    return rcpp_result_gen;
END_RCPP
}
