# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corr_qr_fit <- function(par_, x_, y_, hyper, dim_, gridpars, tauG, muV, SV_, blocks_, blockSizes_, dmcmcpar, imcmcpar) {
    .Call('corrQR_corr_qr_fit', PACKAGE = 'corrQR', par_, x_, y_, hyper, dim_, gridpars, tauG, muV, SV_, blocks_, blockSizes_, dmcmcpar, imcmcpar)
}

