# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corr_qr_fit <- function(par_, x_, y_, hyper_, dim_, A_, R_, LOGDET_, LPGRID_, tauG_, muV_, SV_, blocks_, blockSizes_, dmcmcpar_, imcmcpar_) {
    .Call('corrQR_corr_qr_fit', PACKAGE = 'corrQR', par_, x_, y_, hyper_, dim_, A_, R_, LOGDET_, LPGRID_, tauG_, muV_, SV_, blocks_, blockSizes_, dmcmcpar_, imcmcpar_)
}

devianceCalc <- function(pars_, x_, y_, hyper_, dim_, A_, R_, LOGDET_, LPGRID_, tauG_) {
    .Call('corrQR_devianceCalc', PACKAGE = 'corrQR', pars_, x_, y_, hyper_, dim_, A_, R_, LOGDET_, LPGRID_, tauG_)
}

bivarDensity <- function(newX_, selectY_, neval_, ngrid_, Yeval_, Yres_, pSamples_, hyper_, dim_, A_, R_, LOGDET_, LPGRID_, tauG_, summaryType_) {
    .Call('corrQR_bivarDensity', PACKAGE = 'corrQR', newX_, selectY_, neval_, ngrid_, Yeval_, Yres_, pSamples_, hyper_, dim_, A_, R_, LOGDET_, LPGRID_, tauG_, summaryType_)
}

